#!/bin/bash
#
# Continuous integration script that Jenkins (or whatever) calls which:
# Deploys to dev, staging or production as appropriate

set -u # Variables must be explicit
set -e # If any command fails, fail the whole thing
set -o pipefail

cd ansible
source utilities/init.sh

PS3='What do you want to do? '
options=("View Running Hosts" "Add Domain" "Get Name Server" "Quit")

select opt in "${options[@]}"
do
    case $opt in
        "View Running Hosts")
            ansible-playbook list_running_hosts.yaml -vvv
            ;;
        "Add Domain")
            echo -n "Enter your new domain and press [ENTER]: "
            read domain
            ansible-playbook add_domain.yaml -e domain=$domain -vvv
            ;;
        "Get Name Server")
            echo -n "Enter requested domain and press [ENTER]: "
            read domain
            ansible-playbook get_nameserver.yaml -e domain=$domain -vvv
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done
