---
- name: Find existing instances
  ec2_remote_facts:
    filters:
      "tag:Name": "aws-lamp-virtualhost"
  register: ec2_remote_facts

- name: "Instances found:"
  debug: var=item.id
  with_flattened: "{{ ec2_remote_facts.instances }}"
